version: '3.8'

services:
  rabbitmq1:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret_cookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq1'
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbitmq_cluster
    command: /bin/bash -c "rabbitmq-server"

  rabbitmq2:
    image: rabbitmq:3-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret_cookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq2'
    networks:
      - rabbitmq_cluster
    command: >
      /bin/bash -c "
        sleep 10 &&
        rabbitmq-server -detached &&
        sleep 10 &&
        rabbitmqctl stop_app &&
        rabbitmqctl reset &&
        rabbitmqctl join_cluster rabbit@rabbitmq1 &&
        rabbitmqctl start_app &&
        while true; do sleep 3600; done"

  rabbitmq3:
    image: rabbitmq:3-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret_cookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq3'
    networks:
      - rabbitmq_cluster
    command: >
      /bin/bash -c "
        sleep 10 &&
        rabbitmq-server -detached &&
        sleep 10 &&
        rabbitmqctl stop_app &&
        rabbitmqctl reset &&
        rabbitmqctl join_cluster rabbit@rabbitmq1 &&
        rabbitmqctl start_app &&
        while true; do sleep 3600; done"

networks:
  rabbitmq_cluster:
    driver: bridge 