version: '3.8'

services:
  rabbitmq1:
    image: rabbitmq:3.13-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret_cookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq1'
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbitmq_cluster

  rabbitmq2:
    image: rabbitmq:3-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret_cookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq2'
    ports:
      - "15673:15672"
      - "5673:5672"
    networks:
      - rabbitmq_cluster

  rabbitmq3:
    image: rabbitmq:3-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret_cookie'
      RABBITMQ_NODENAME: 'rabbit@rabbitmq3'
    ports:
      - "15674:15672"
      - "5674:5672"
    networks:
      - rabbitmq_cluster
networks:
  rabbitmq_cluster:
    driver: bridge 